package model

import (
	"time"
)

// --- INPUT TYPES ---
// Input types are generated by gqlgen in graph/model.
// We only define core domain models here.

// --- CORE DATABASE MODEL (Used for Output) ---

// Maps to the GraphQL 'WorkoutLog' and MongoDB storage
type WorkoutLog struct {
	ID           string         `json:"id" bson:"_id,omitempty"`
	UserID       string         `json:"userId" bson:"userId"`
	Name         string         `json:"name" bson:"name"`
	StartTime    time.Time      `json:"startTime" bson:"startTime"`
	EndTime      time.Time      `json:"endTime" bson:"endTime"`
	ExerciseLogs []*ExerciseLog `json:"exerciseLogs" bson:"exerciseLogs"`
	LocationName *string        `json:"locationName" bson:"locationName"`
	GeneralNotes *string        `json:"generalNotes" bson:"generalNotes"`
}

type ExerciseLog struct {
	UniqueExerciseID string  `json:"uniqueExerciseId" bson:"uniqueExerciseId"`
	Sets             []*Set  `json:"sets" bson:"sets"`
	Notes            *string `json:"notes" bson:"notes"`
}

type Set struct {
	Reps      int32   `json:"reps" bson:"reps"`
	Weight    float64 `json:"weight" bson:"weight"`
	Rpe       *int32  `json:"rpe" bson:"rpe"`
	ToFailure *bool   `json:"toFailure" bson:"toFailure"`
	Order     int32   `json:"order" bson:"order"`
}

type WeightUnit string

const (
	WeightUnitKilograms WeightUnit = "KILOGRAMS"
	WeightUnitPounds    WeightUnit = "POUNDS"
)

type UniqueExercise struct {
	ID          string  `json:"id" bson:"_id,omitempty"`
	Name        string  `json:"name" bson:"name"`
	UserID      *string `json:"userId,omitempty" bson:"userId,omitempty"` // nil for System exercises
	Description *string `json:"description,omitempty" bson:"description,omitempty"`
}
