// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	User    *User  `json:"user,omitempty"`
}

type CreateWorkoutLogInput struct {
	Name         string              `json:"name"`
	StartTime    time.Time           `json:"startTime"`
	EndTime      time.Time           `json:"endTime"`
	ExerciseLogs []*ExerciseLogInput `json:"exerciseLogs"`
	LocationName *string             `json:"locationName,omitempty"`
	GeneralNotes *string             `json:"generalNotes,omitempty"`
}

type ExerciseLog struct {
	UniqueExerciseID string  `json:"uniqueExerciseId"`
	Sets             []*Set  `json:"sets"`
	Notes            *string `json:"notes,omitempty"`
}

type ExerciseLogInput struct {
	UniqueExerciseID string      `json:"uniqueExerciseId"`
	Sets             []*SetInput `json:"sets"`
	Notes            *string     `json:"notes,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Set struct {
	Reps      int32   `json:"reps"`
	Weight    float64 `json:"weight"`
	Rpe       *int32  `json:"rpe,omitempty"`
	ToFailure *bool   `json:"toFailure,omitempty"`
	Order     int32   `json:"order"`
}

type SetInput struct {
	Reps      int32      `json:"reps"`
	Weight    float64    `json:"weight"`
	Unit      WeightUnit `json:"unit"`
	Rpe       *int32     `json:"rpe,omitempty"`
	ToFailure *bool      `json:"toFailure,omitempty"`
	Order     int32      `json:"order"`
}

type UpdateUserInput struct {
	Email           *string `json:"email,omitempty"`
	CurrentPassword string  `json:"currentPassword"`
	NewPassword     *string `json:"newPassword,omitempty"`
	PreferredUnit   *string `json:"preferredUnit,omitempty"`
}

type User struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	PreferredUnit string `json:"preferredUnit"`
}

type WorkoutLog struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	StartTime    time.Time      `json:"startTime"`
	EndTime      time.Time      `json:"endTime"`
	ExerciseLogs []*ExerciseLog `json:"exerciseLogs"`
	LocationName *string        `json:"locationName,omitempty"`
	GeneralNotes *string        `json:"generalNotes,omitempty"`
}

type WeightUnit string

const (
	WeightUnitKilograms WeightUnit = "KILOGRAMS"
	WeightUnitPounds    WeightUnit = "POUNDS"
)

var AllWeightUnit = []WeightUnit{
	WeightUnitKilograms,
	WeightUnitPounds,
}

func (e WeightUnit) IsValid() bool {
	switch e {
	case WeightUnitKilograms, WeightUnitPounds:
		return true
	}
	return false
}

func (e WeightUnit) String() string {
	return string(e)
}

func (e *WeightUnit) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WeightUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WeightUnit", str)
	}
	return nil
}

func (e WeightUnit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WeightUnit) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WeightUnit) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
