// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/riverajo/fitness-app/backend/internal/model"
)

type AuthPayload struct {
	Success      bool        `json:"success"`
	Message      string      `json:"message"`
	User         *model.User `json:"user,omitempty"`
	Token        string      `json:"token"`
	RefreshToken string      `json:"refreshToken"`
}

type CreateUniqueExerciseInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateWorkoutLogInput struct {
	Name         string              `json:"name"`
	StartTime    time.Time           `json:"startTime"`
	EndTime      time.Time           `json:"endTime"`
	ExerciseLogs []*ExerciseLogInput `json:"exerciseLogs"`
	LocationName *string             `json:"locationName,omitempty"`
	GeneralNotes *string             `json:"generalNotes,omitempty"`
}

type ExerciseLogInput struct {
	UniqueExerciseID string      `json:"uniqueExerciseId"`
	Sets             []*SetInput `json:"sets"`
	Notes            *string     `json:"notes,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SetInput struct {
	Reps      int32            `json:"reps"`
	Weight    float64          `json:"weight"`
	Unit      model.WeightUnit `json:"unit"`
	Rpe       *int32           `json:"rpe,omitempty"`
	ToFailure *bool            `json:"toFailure,omitempty"`
	Order     int32            `json:"order"`
}

type UpdateUserInput struct {
	Email           *string           `json:"email,omitempty"`
	CurrentPassword string            `json:"currentPassword"`
	NewPassword     *string           `json:"newPassword,omitempty"`
	PreferredUnit   *model.WeightUnit `json:"preferredUnit,omitempty"`
}

type UpdateWorkoutLogInput struct {
	ID           string              `json:"id"`
	Name         *string             `json:"name,omitempty"`
	StartTime    *time.Time          `json:"startTime,omitempty"`
	EndTime      *time.Time          `json:"endTime,omitempty"`
	ExerciseLogs []*ExerciseLogInput `json:"exerciseLogs,omitempty"`
	LocationName *string             `json:"locationName,omitempty"`
	GeneralNotes *string             `json:"generalNotes,omitempty"`
}
